export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

//YEARS For Every Machine
export const N2_YEARS = "N2_YEARS";
export const N2_PLUS_150_YEARS = "N2_PLUS_150_YEARS";
export const N2_PLUS_50_YEARS = "N2_PLUS_50_YEARS";

//Months of Year For Every Machine
export const N2_MONTHS = "N2_MONTHS";
export const N2_PLUS_150_MONTHS = "N2_PLUS_150_MONTHS";
export const N2_PLUS_50_MONTHS = "N2_PLUS_50_MONTHS";

//Weeks
export const N2_WEEKS = "N2_WEEKS";
export const N2_PLUS_150_WEEKS = "N2_PLUS_150_WEEKS";
export const N2_PLUS_50_WEEKS = "N2_PLUS_50_WEEKS";

//Week CHART DATA
export const N2_WEEK_CHART_DATA = "N2_WEEK_CHART_DATA";
export const N2_PLUS_150_WEEK_CHART_DATA = "N2_PLUS_150_WEEK_CHART_DATA";
export const N2_PLUS_50_WEEK_CHART_DATA = "N2_PLUS_50_WEEK_CHART_DATA";


//Month CHART DATA
export const N2_MONTH_CHART_DATA = "N2_MONTH_CHART_DATA";
export const N2_PLUS_150_MONTH_CHART_DATA = "N2_PLUS_150_MONTH_CHART_DATA";
export const N2_PLUS_50_MONTH_CHART_DATA = "N2_PLUS_50_MONTH_CHART_DATA";

//Year CHART DATA
export const N2_YEAR_CHART_DATA = "N2_YEAR_CHART_DATA";
export const N2_PLUS_150_YEAR_CHART_DATA = "N2_PLUS_150_YEAR_CHART_DATA";
export const N2_PLUS_50_YEAR_CHART_DATA = "N2_PLUS_50_YEAR_CHART_DATA";


//WEEK TABLE DATA
export const N2_WEEK_TABLE_DATA = "N2_WEEK_TABLE_DATA";
export const N2_PLUS_150_WEEK_TABLE_DATA = "N2_PLUS_150_WEEK_TABLE_DATA";
export const N2_PLUS_50_WEEK_TABLE_DATA = "N2_PLUS_50_WEEK_TABLE_DATA";

//RATIOS
export const RATIOS = "RATIOS";

//DATES
export const N2_SELECT_DATE = "N2_SELECT_DATE";
export const N2_PLUS_150_SELECT_DATE = "N2_PLUS_150_SELECT_DATE";
export const N2_PLUS_50_SELECT_DATE = "N2_PLUS_50_SELECT_DATE";

// Commercial Rates Values
export const QUOTES_NUMBER = "QUOTES_NUMBER";
export const CLIENTS = "CLIENTS";
export const TURNOVER = "TURNOVER";

//NOTIFICATION Errors 
export const NOTIFICATION_ERROR = "NOTIFICATION_ERROR";

//NOTIFICATION SUCCESS
export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";

//NOTIFICATION WARNING
export const NOTIFICATION_WARNING = "NOTIFICATION_WARNING";

//NOTIFICATION INFO
export const NOTIFICATION_INFO = "NOTIFICATION_INFO";

//USERS LIST
export const USERS_LIST = "USERS_LIST";

