export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_N2 = 'GET_N2';
export const GET_N2_PLUS_150 = 'GET_N2_PLUS_150';
export const GET_N2_PLUS_50 = 'GET_N2_PLUS_50';


//YEARS For Every Machine
export const N2_YEARS = "N2_YEARS";
export const N2_PLUS_150_YEARS = "N2_PLUS_150_YEARS";
export const N2_PLUS_50_YEARS = "N2_PLUS_50_YEARS";

//Months of Year For Every Machine
export const N2_MONTHS = "N2_MONTHS";
export const N2_PLUS_150_MONTHS = "N2_PLUS_150_MONTHS";
export const N2_PLUS_50_MONTHS = "N2_PLUS_50_MONTHS";

//Weeks
export const N2_WEEKS = "N2_WEEKS";
export const N2_PLUS_150_WEEKS = "N2_PLUS_150_WEEKS";
export const N2_PLUS_50_WEEKS = "N2_PLUS_50_WEEKS";

//Week CHART DATA
export const N2_WEEK_CHART_DATA = "N2_WEEK_CHART_DATA";
export const N2_PLUS_150_WEEK_CHART_DATA = "N2_PLUS_150_WEEK_CHART_DATA";
export const N2_PLUS_50_WEEK_CHART_DATA = "N2_PLUS_50_WEEK_CHART_DATA";


//Month CHART DATA
export const N2_MONTH_CHART_DATA = "N2_MONTH_CHART_DATA";
export const N2_PLUS_150_MONTH_CHART_DATA = "N2_PLUS_150_MONTH_CHART_DATA";
export const N2_PLUS_50_MONTH_CHART_DATA = "N2_PLUS_50_MONTH_CHART_DATA";

//Year CHART DATA
export const N2_YEAR_CHART_DATA = "N2_MONTH_CHART_DATA";
export const N2_PLUS_150_YEAR_CHART_DATA = "N2_PLUS_150_MONTH_CHART_DATA";
export const N2_PLUS_50_YEAR_CHART_DATA = "N2_PLUS_50_MONTH_CHART_DATA";